name: "🧪 Tests"

on:
  workflow_dispatch:
    inputs:
      filter:
        type: string
        description: Filter tests
        default: ""
  workflow_call:
    inputs:
      filter:
        type: string
  # push:
  #   branches:
  #     - master
  #   paths:
  #     - "packages/duskmoonui/functions/**"
  #     - "packages/duskmoonui/src/**"
  #     - "packages/docs/src/**"
jobs:
  tests:
    timeout-minutes: 10
    env:
      filter: ${{ inputs.filter }}
    name: "Tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          clean: false

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun i

      - name: build package
        run: |
          cd packages/duskmoonui
          bun run prebuild
          cd ../..
          bun run --bun build

      - name: Run tests
        run: |
          if [ -z "${{ env.filter }}" ]; then
            bun test
          else
            bun test -t ${{ env.filter }}
          fi
